/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

/**
 *
 * @author marco
 */
public class Calculadora extends javax.swing.JFrame {

    double[] numeros = new double[2];
    boolean decimal = false;
    boolean division = false;
    boolean mult = false;
    boolean resta = false;
    boolean suma = false;

    public Calculadora() {
        initComponents();
        setResizable(false);
        setSize(335, 440);
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        btn_borrar = new javax.swing.JButton();
        btn_signo = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        btn_divi = new javax.swing.JButton();
        btn_mult = new javax.swing.JButton();
        btn_resta = new javax.swing.JButton();
        btn_suma = new javax.swing.JButton();
        btn_9 = new javax.swing.JButton();
        btn_8 = new javax.swing.JButton();
        btn_7 = new javax.swing.JButton();
        btn_6 = new javax.swing.JButton();
        btn_5 = new javax.swing.JButton();
        btn_4 = new javax.swing.JButton();
        btn_3 = new javax.swing.JButton();
        btn_2 = new javax.swing.JButton();
        btn_1 = new javax.swing.JButton();
        btn_punto = new javax.swing.JButton();
        btn_0 = new javax.swing.JButton();
        btn_igual = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel_ventana = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btn_borrar.setBackground(new java.awt.Color(51, 51, 51));
        btn_borrar.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_borrar.setForeground(new java.awt.Color(255, 255, 255));
        btn_borrar.setText("AC");
        btn_borrar.setFocusable(false);
        btn_borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_borrarActionPerformed(evt);
            }
        });
        jPanel2.add(btn_borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 70, 40));

        btn_signo.setBackground(new java.awt.Color(51, 51, 51));
        btn_signo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_signo.setForeground(new java.awt.Color(255, 255, 255));
        btn_signo.setText("+/-");
        btn_signo.setFocusable(false);
        btn_signo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_signoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_signo, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, 70, 40));

        jButton2.setBackground(new java.awt.Color(51, 51, 51));
        jButton2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText(" ");
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 70, 40));

        btn_divi.setBackground(new java.awt.Color(153, 153, 153));
        btn_divi.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_divi.setForeground(new java.awt.Color(255, 255, 255));
        btn_divi.setText("/");
        btn_divi.setFocusable(false);
        btn_divi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_diviActionPerformed(evt);
            }
        });
        jPanel2.add(btn_divi, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 70, 40));

        btn_mult.setBackground(new java.awt.Color(153, 153, 153));
        btn_mult.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_mult.setForeground(new java.awt.Color(255, 255, 255));
        btn_mult.setText("*");
        btn_mult.setFocusable(false);
        btn_mult.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_multActionPerformed(evt);
            }
        });
        jPanel2.add(btn_mult, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 60, 70, 40));

        btn_resta.setBackground(new java.awt.Color(153, 153, 153));
        btn_resta.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_resta.setForeground(new java.awt.Color(255, 255, 255));
        btn_resta.setText("-");
        btn_resta.setFocusable(false);
        btn_resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_restaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_resta, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 110, 70, 40));

        btn_suma.setBackground(new java.awt.Color(153, 153, 153));
        btn_suma.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_suma.setForeground(new java.awt.Color(255, 255, 255));
        btn_suma.setText("+");
        btn_suma.setFocusable(false);
        btn_suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sumaActionPerformed(evt);
            }
        });
        jPanel2.add(btn_suma, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 70, 40));

        btn_9.setBackground(new java.awt.Color(255, 255, 255));
        btn_9.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_9.setForeground(new java.awt.Color(0, 0, 0));
        btn_9.setText("9");
        btn_9.setFocusable(false);
        btn_9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_9ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_9, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 60, 70, 40));

        btn_8.setBackground(new java.awt.Color(255, 255, 255));
        btn_8.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_8.setForeground(new java.awt.Color(0, 0, 0));
        btn_8.setText("8");
        btn_8.setFocusable(false);
        btn_8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_8ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_8, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 60, 70, 40));

        btn_7.setBackground(new java.awt.Color(255, 255, 255));
        btn_7.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_7.setForeground(new java.awt.Color(0, 0, 0));
        btn_7.setText("7");
        btn_7.setFocusable(false);
        btn_7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_7ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, 70, 40));

        btn_6.setBackground(new java.awt.Color(255, 255, 255));
        btn_6.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_6.setForeground(new java.awt.Color(0, 0, 0));
        btn_6.setText("6");
        btn_6.setFocusable(false);
        btn_6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_6ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_6, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 110, 70, 40));

        btn_5.setBackground(new java.awt.Color(255, 255, 255));
        btn_5.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_5.setForeground(new java.awt.Color(0, 0, 0));
        btn_5.setText("5");
        btn_5.setFocusable(false);
        btn_5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_5ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 110, 70, 40));

        btn_4.setBackground(new java.awt.Color(255, 255, 255));
        btn_4.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_4.setForeground(new java.awt.Color(0, 0, 0));
        btn_4.setText("4");
        btn_4.setFocusable(false);
        btn_4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_4ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 70, 40));

        btn_3.setBackground(new java.awt.Color(255, 255, 255));
        btn_3.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_3.setForeground(new java.awt.Color(0, 0, 0));
        btn_3.setText("3");
        btn_3.setFocusable(false);
        btn_3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_3ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 160, 70, 40));

        btn_2.setBackground(new java.awt.Color(255, 255, 255));
        btn_2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_2.setForeground(new java.awt.Color(0, 0, 0));
        btn_2.setText("2");
        btn_2.setFocusable(false);
        btn_2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_2ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 160, 70, 40));

        btn_1.setBackground(new java.awt.Color(255, 255, 255));
        btn_1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_1.setForeground(new java.awt.Color(0, 0, 0));
        btn_1.setText("1");
        btn_1.setFocusable(false);
        btn_1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_1ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 160, 70, 40));

        btn_punto.setBackground(new java.awt.Color(255, 255, 255));
        btn_punto.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_punto.setForeground(new java.awt.Color(0, 0, 0));
        btn_punto.setText(".");
        btn_punto.setFocusable(false);
        btn_punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_puntoActionPerformed(evt);
            }
        });
        jPanel2.add(btn_punto, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 70, 40));

        btn_0.setBackground(new java.awt.Color(255, 255, 255));
        btn_0.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_0.setForeground(new java.awt.Color(0, 0, 0));
        btn_0.setText("0");
        btn_0.setFocusable(false);
        btn_0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_0ActionPerformed(evt);
            }
        });
        jPanel2.add(btn_0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 140, 40));

        btn_igual.setBackground(new java.awt.Color(153, 153, 153));
        btn_igual.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        btn_igual.setForeground(new java.awt.Color(255, 255, 255));
        btn_igual.setText("=");
        btn_igual.setFocusable(false);
        btn_igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_igualActionPerformed(evt);
            }
        });
        jPanel2.add(btn_igual, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 210, 70, 40));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 320, 260));

        jLabel2.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jLabel2.setText("Estandar");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 49));
        jLabel2.getAccessibleContext().setAccessibleDescription("");

        jLabel_ventana.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel_ventana.setForeground(new java.awt.Color(0, 0, 0));
        jLabel_ventana.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jPanel1.add(jLabel_ventana, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 310, 41));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 330, 400));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btn_signoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_signoActionPerformed
        // Cambiar signos
        try {
            double cambio;
            String entero;
            cambio = Double.parseDouble(jLabel_ventana.getText());
            cambio = cambio * -1;
            if (cambio % 1 == 0) {
                entero = Double.toString(cambio);
                jLabel_ventana.setText(entero.substring(0, entero.length() - 2));
            } else {
                jLabel_ventana.setText(Double.toString(cambio));
            }

        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_signoActionPerformed

    private void btn_igualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_igualActionPerformed
        //resultado
        double resultado;
        String entero;
        try {
            numeros[1] = Double.parseDouble(jLabel_ventana.getText());
            if (division == true) {

                if (numeros[1] == 0) {
                    jLabel_ventana.setText("error");
                } else {
                    resultado = numeros[0] / numeros[1];

                    if (resultado % 1 == 0) {
                        entero = Double.toString(resultado);
                        jLabel_ventana.setText(entero.substring(0, entero.length() - 2));
                    } else {
                        jLabel_ventana.setText(Double.toString(resultado));
                    }
                }

            } else if (mult == true) {
                resultado = numeros[0] * numeros[1];
                if (resultado % 1 == 0) {
                    entero = Double.toString(resultado);
                    jLabel_ventana.setText(entero.substring(0, entero.length() - 2));
                } else {
                    jLabel_ventana.setText(Double.toString(resultado));
                }
            } else if (resta == true) {
                resultado = numeros[0] - numeros[1];
                if (resultado % 1 == 0) {
                    entero = Double.toString(resultado);
                    jLabel_ventana.setText(entero.substring(0, entero.length() - 2));
                } else {
                    jLabel_ventana.setText(Double.toString(resultado));
                }
            } else if (suma == true) {
                resultado = numeros[0] + numeros[1];
                if (resultado % 1 == 0) {
                    entero = Double.toString(resultado);
                    jLabel_ventana.setText(entero.substring(0, entero.length() - 2));
                } else {
                    jLabel_ventana.setText(Double.toString(resultado));
                }
            }
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_igualActionPerformed

    private void btn_borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_borrarActionPerformed
//borrar
        jLabel_ventana.setText(" ");
        decimal = false;
        division = false;
        mult = false;
        resta = false;
        suma = false;
    }//GEN-LAST:event_btn_borrarActionPerformed

    private void btn_9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_9ActionPerformed
        // 9
        jLabel_ventana.setText(jLabel_ventana.getText() + "9");
    }//GEN-LAST:event_btn_9ActionPerformed

    private void btn_multActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_multActionPerformed
        // multiplicacion
        try {
            numeros[0] = Double.parseDouble(jLabel_ventana.getText());
            jLabel_ventana.setText(" ");
            mult = true;
            decimal = true;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_multActionPerformed

    private void btn_restaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_restaActionPerformed
        // resta
        try {
            numeros[0] = Double.parseDouble(jLabel_ventana.getText());
            jLabel_ventana.setText(" ");
            resta = true;
            decimal = true;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_restaActionPerformed

    private void btn_sumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sumaActionPerformed
        // suma
        try {
            numeros[0] = Double.parseDouble(jLabel_ventana.getText());
            jLabel_ventana.setText(" ");
            suma = true;
            decimal = true;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_sumaActionPerformed

    private void btn_diviActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_diviActionPerformed
        //division
        try {
            numeros[0] = Double.parseDouble(jLabel_ventana.getText());
            jLabel_ventana.setText(" ");
            division = true;
            decimal = true;
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btn_diviActionPerformed

    private void btn_7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_7ActionPerformed
        // 7
        jLabel_ventana.setText(jLabel_ventana.getText() + "7");
    }//GEN-LAST:event_btn_7ActionPerformed

    private void btn_8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_8ActionPerformed
        // 8
        jLabel_ventana.setText(jLabel_ventana.getText() + "8");
    }//GEN-LAST:event_btn_8ActionPerformed

    private void btn_6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_6ActionPerformed
        // 6
        jLabel_ventana.setText(jLabel_ventana.getText() + "6");
    }//GEN-LAST:event_btn_6ActionPerformed

    private void btn_5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_5ActionPerformed
        // 5
        jLabel_ventana.setText(jLabel_ventana.getText() + "5");
    }//GEN-LAST:event_btn_5ActionPerformed

    private void btn_4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_4ActionPerformed
        // 4
        jLabel_ventana.setText(jLabel_ventana.getText() + "4");
    }//GEN-LAST:event_btn_4ActionPerformed

    private void btn_2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_2ActionPerformed
        // 2
        jLabel_ventana.setText(jLabel_ventana.getText() + "2");
    }//GEN-LAST:event_btn_2ActionPerformed

    private void btn_3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_3ActionPerformed
        // 3
        jLabel_ventana.setText(jLabel_ventana.getText() + "3");
    }//GEN-LAST:event_btn_3ActionPerformed

    private void btn_puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_puntoActionPerformed
        // Punto
        if (decimal == false) {
            jLabel_ventana.setText(jLabel_ventana.getText() + ".");
            decimal = true;
        }
    }//GEN-LAST:event_btn_puntoActionPerformed

    private void btn_1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_1ActionPerformed
        // 1
        jLabel_ventana.setText(jLabel_ventana.getText() + "1");
    }//GEN-LAST:event_btn_1ActionPerformed

    private void btn_0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_0ActionPerformed
        // 0
        jLabel_ventana.setText(jLabel_ventana.getText() + "0");
    }//GEN-LAST:event_btn_0ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_0;
    private javax.swing.JButton btn_1;
    private javax.swing.JButton btn_2;
    private javax.swing.JButton btn_3;
    private javax.swing.JButton btn_4;
    private javax.swing.JButton btn_5;
    private javax.swing.JButton btn_6;
    private javax.swing.JButton btn_7;
    private javax.swing.JButton btn_8;
    private javax.swing.JButton btn_9;
    private javax.swing.JButton btn_borrar;
    private javax.swing.JButton btn_divi;
    private javax.swing.JButton btn_igual;
    private javax.swing.JButton btn_mult;
    private javax.swing.JButton btn_punto;
    private javax.swing.JButton btn_resta;
    private javax.swing.JButton btn_signo;
    private javax.swing.JButton btn_suma;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel_ventana;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
